### PR TITLE
[DRAFT] python: init

### PR DESCRIPTION
**Pull request by Infinidoge**
Implements FlexVer in Python via the `FlexVer` class, which implements total ordering.

TODO:
- [ ] Respect #10 
- [x] Handle #12 
- [ ] Finish publishing to PyPI

Aggreement:
- [x] I own the full rights to my contribution, and agree to release it under the terms of the Creative Commons Zero Public Domain Dedication

### CODE REVIEW

**Review by exaskye — APPROVED** [review]
LGTM. Will ask for others that know Python to leave a review, since I have no idea what is and isn't 𝓟𝔂𝓽𝓱𝓸𝓷𝓲𝓬.

**Comment by exaskye** [comment]
#10 has been merged; please port your tests to the new file-based test cases. You will likely also need to implement the fix for #12.

**Comment by ENDERZOMBI102** [comment]
what is missing in this PR? i would be interested into using FlexVer from python

**Comment by exaskye** [comment]
Closing in favor of #22, as Infinidoge seems to have abandoned this PR.

**Pull request closed without merging**
